drop table IF EXISTS CANDLE_1MINUTE DELETE TOPIC;
drop table IF EXISTS CANDLE_10MINUTE DELETE TOPIC;
drop table IF EXISTS CANDLE_1HOUR DELETE TOPIC;
drop table IF EXISTS CANDLE_1DAY DELETE TOPIC;
drop stream IF EXISTS stock_ticks DELETE TOPIC;